---
name: test

on:
  push:
    branches:
      - main
    paths:
      - '**.rs'
      - 'Cargo.*'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**.rs'
      - 'Cargo.*'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cargo test
      - name: Check
        run: cargo check
      - name: Build
        run: cargo build
